# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr:
  autoCancel: true
  branches:
    include:
    - development

jobs:
- job: BuildAndTest
  timeoutInMinutes: 180 # how long to run the job before automatically cancelling
  pool: oracle-cloud
  steps:
  - task: CMake@1
    displayName: 'Configure CMake'
    inputs:
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DAMReX_SPACEDIM=1'

  - task: CMake@1
    displayName: 'Build Quokka'
    inputs:
      cmakeArgs: '--build .'

  - task: CMake@1
    displayName: 'Run CTest'
    inputs:
      cmakeArgs: '-E chdir . ctest -j 2 -T Test --output-on-failure'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: build/Testing/*/Test.xml
      testRunTitle: $(Agent.JobName)
    condition: succeededOrFailed()
    displayName: Publish test results
