trigger:
- development

pr:
  autoCancel: true
  branches:
    include:
    - development

pool: avatar

steps:

- task: CMake@1
  displayName: 'Configure CMake'
  inputs:
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CUDA_COMPILER=clang -DAMReX_SPACEDIM=3 -DAMReX_GPU_BACKEND=CUDA -DCMAKE_CUDA_ARCHITECTURES=70 -DQUOKKA_PYTHON=OFF -G Ninja'

- task: CMake@1
  displayName: 'Build Quokka'
  inputs:
    cmakeArgs: '--build .'

- task: CMake@1
  displayName: 'Run CTest'
  inputs:
    cmakeArgs: '-E chdir . ctest -E "MatterEnergyExchange*" -T Test --output-on-failure'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: cTest
    testResultsFiles: build/Testing/*/Test.xml
    testRunTitle: $(Agent.JobName)
  condition: succeededOrFailed()
  displayName: Publish test results